http:
  routers:
    tactical-rmm-http:
      entryPoints:
        - "web"
      rule: "Host(`rmm.yourdomain.com`)"
      middlewares:
        - globalHeaders
        - redirect-to-https@docker
        - gzip@docker
      service: "tactical-rmm"
    tactical-rmm:
      entryPoints:
        - "websecure"
      rule: "Host(`rmm.yourdomain.com`)"
      middlewares:
        - globalHeaders
        - secureHeaders
        - gzip@docker
      service: "tactical-rmm"
      tls:
        options: securetls@file
        certResolver: google
        domains:
          - main: "yourdomain.com"
            sans:
              - "*.yourdomain.com"

    tactical-mesh-http:
      entryPoints:
        - "web"
      rule: "Host(`mesh.yourdomain.com`)"
      middlewares:
        - globalHeaders
        - redirect-to-https@docker
        - gzip@docker
      service: "tactical-mesh"
    tactical-mesh:
      entryPoints:
        - "websecure"
      rule: "Host(`mesh.yourdomain.com`)"
      service: "tactical-mesh"
      tls:
        options: securetls@file
        certResolver: google
        domains:
          - main: "yourdomain.com"
            sans:
              - "*.yourdomain.com"

    tactical-api-http:
      entryPoints:
        - "web"
      rule: "Host(`api.yourdomain.com`)"
      middlewares:
        - globalHeaders
        - redirect-to-https@docker
        - gzip@docker
      service: "tactical-api"
    tactical-api:
      entryPoints:
        - "websecure"
      rule: "Host(`api.yourdomain.com`)"
      middlewares:
        - globalHeaders
        - secureHeaders
        - gzip@docker
      service: "tactical-api"
      tls:
        options: securetls@file
        certResolver: google
        domains:
          - main: "yourdomain.com"
            sans:
              - "*.yourdomain.com"

  services:
    tactical-rmm:
      loadBalancer:
        servers:
          - url: "https://rmm.yourdomain.com:4443"

    tactical-mesh:
      loadBalancer:
        servers:
          - url: "https://mesh.yourdomain.com:4443"

    tactical-api:
      loadBalancer:
        servers:
          - url: "https://api.yourdomain.com:4443"
